### ISSUE TITLE
Can I set the documentID with object.save

### ISSUE THREAD

**Issue by Pepino-GR** [1amageek/Pring#15]
For my application it is important to set the documentID with the .save Method. Is it planed, or is it implemented?

**Comment by 1amageek** [comment]
https://github.com/1amageek/Pring/blob/master/Pring/Object.swift#L92

Of course I'm implementing it

**Comment by Pepino-GR** [comment]
Thanks a lot for your very quick answer. When will it be included?

**Comment by 1amageek** [comment]
Sorry, it was a mistake. Already implemented

**Comment by Pepino-GR** [comment]
So I can use object.save(myDocumentID) ?

**Comment by Pepino-GR** [comment]
Sorry, I see it in your Readme Change. Thanks a lot

**Comment by coffieDona** [comment]
How can I create binary tree MLM in firebase

**Comment by 1amageek** [comment]
@coffieDona ?
