### ISSUE TITLE
Object.update doesn't persist changes

### ISSUE THREAD

**Issue by adeeldb** [1amageek/Pring#16]
After fetching an object from the database, setting a property of the object and calling .update() doesn't give any errors, but also doesn't reflect the changes in the database. Tried using object.reference.updateData(object.value) instead and it works as expected.

**Comment by 1amageek** [comment]
I'm sorry.
I fixed a bug. Please try with the new version. Please contact us if there is a problem.

**Comment by adeeldb** [comment]
Verified to be resolved in the latest release.
