### ISSUE TITLE
Bugs documentation

### ISSUE THREAD

**Issue by mosn** [1amageek/Pring#2]
The readme suggests that the library contains bug, could you document them in issues so that can be visible and get to by someone who has the time. 

Thanks

**Comment by 1amageek** [comment]
Thank you for posting.

OK, let's clarify as much as possible.

**Comment by 1amageek** [comment]
I updated the README.
Is there any other unclear point?

**Comment by moia-mohsen** [comment]
Everything is clear, thanks a lot. 

On Firestore model and DataSource, one way to handle would be to use firestore's `DocumentSnapshot` to manage various operations. That could save time and prevent reimplementation. 

just a thought

**Comment by mosn** [comment]
Everything is clear. 

I think one way would be to use `DocumentSnapshot` as a service that can handle Firestore operations. That way we don't have to reimplement services that is offered by SDK. 

Just a thought
