### ISSUE TITLE
Customize "Object" variables

### ISSUE THREAD

**Issue by madsodgaard** [1amageek/Pring#22]
Hello.

I don't quite fully understand why /version/1/ is a required prefix?

Is it possible to change this, and maybe also override the modelName variable?

/ Mads

**Comment by 1amageek** [comment]
This prefix means that it corresponds to migration.

Migration of Document can be done very easily if you just add a property. However, when doing destructive modification, version control is necessary.

**Comment by 1amageek** [comment]
For details on Customizing Document, please click here
https://github.com/1amageek/Pring/blob/master/PringTests/CustomDocument.swift

**Comment by madsodgaard** [comment]
Okay, thank you that reference.

It seems that the object class cannot save a "GeoPoint", it saves all the other data associated with the class I created, except the GeoPoint. It has a value on the device.

Do you want me to create a new issue?

**Comment by 1amageek** [comment]
Yes, please create

**Comment by cerupcat** [comment]
It doesn't seem possible to override the variables. I get "Overriding non-@objc declarations from extensions is not supported". @1amageek is there a solution for not prefixing with "version/". I already have data in my database that doesn't follow this convention. Without the ability to remove this requirement, it's not possible to get my data.
