### ISSUE TITLE
Numbers are not allowed when using Cloud Functions

### ISSUE THREAD

**Issue by madsodgaard** [1amageek/Pring#25]
As of now as all collections need the prefix "version/1" etc. It disables our ability to use Cloud Functions. Cloud Functions does not allow numbers in the regex, I've just tried and it complains about the "1" being there. 

How do we prevent this from happening?

**Comment by madsodgaard** [comment]
Okay, maybe it is not that it's a numeric value that is the problem.

This is the error I get:

fieldViolations=[field=event_trigger, description=Expected value version/test/user/{userId}/activeClub to match regular expression [^/]+/[^/]+(/[^/]+/[^/]+)*]]

**Comment by 1amageek** [comment]
We are using CloudFunctions.
I do not understand what you are having troubled with this.

Please tell me about source and error contents.

**Comment by madsodgaard** [comment]
Sorry. This was due to me pointing to a certain field, I read the Firestore documentation, and learned this is not possible. Thanks.

Is it possible to prevent /version/1 prefix? this makes it complicated to make Cloud Functions ex.

**Comment by 1amageek** [comment]
Hi. It is possible. override this function.

https://github.com/1amageek/Pring/blob/master/Pring/Object.swift#L23
