### ISSUE TITLE
Error on pack().commit not resolved

### ISSUE THREAD

**Issue by MRzr** [1amageek/Pring#3]
When there is error saving document to firebase error object is ignored and you continue with getDocument method. I think error message is quite important here (bad permissions etc.)

My solution  is to return nil reference and error object if there is any and perform getDocument only where there is no error in save.

https://github.com/1amageek/Pring/blob/d92cd5d301eccd81b22120e9f8ba0f9a3c1b0dc0/Pring/Object.swift#L327

**Comment by 1amageek** [comment]
Thank you for Message.
I think that you are right.I will correct it soon.

**Comment by MRzr** [comment]
You're welcome. Keep up good work!
