### ISSUE TITLE
Build failure in Xcode 9.3

### ISSUE THREAD

**Issue by starhoshi** [1amageek/Pring#31]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 9.3 (9E145)
  * Pring version: 0.7.14

### [REQUIRED] Step 3: Describe the problem

Our project cannot build in Xcode 9.3.

```
for 'deleteFiles(container:block:)' at /Users/hoge/Xcode/Komerco/Pods/Pring/Pring/AnySubCollection.swift:57:12
error: Segmentation fault: 11
```

**Comment by 1amageek** [comment]
@starhoshi Thank you for your message. 
I fixed it.

**Comment by starhoshi** [comment]
Thanks!
