### ISSUE TITLE
Store object

### ISSUE THREAD

**Issue by brightsider** [1amageek/Pring#39]
Hello!
How I can to store Object for reusing?
Needs UserDefaults or any other storage.

**Comment by 1amageek** [comment]
I used to make a Chat application by connecting Firestore and Realm. How about this reference?

https://github.com/1amageek/Msg
https://github.com/1amageek/Msg/blob/master/Msg/Box.swift

Basically the same is true for UserDefaults and CoreData.
Get the data, transfer the data, save it.

I think Firestore's caching function is enough. But User's data needs to be considered.

-- 

Now I stop using it and I am making a new project for Firestore alone.

https://github.com/1amageek/Muni
