### ISSUE TITLE
Reference path issue

### ISSUE THREAD

**Issue by brightsider** [1amageek/Pring#42]
I have cards in user and set this card to Item.
Card path - version/1/user/ID/cards/ID
Card path in item.card.get - version/1/card/ID

**Comment by 1amageek** [comment]
You can do it easily with NestedCollection.

**Comment by 1amageek** [comment]
Attach the source code necessary for understanding.

**Comment by brightsider** [comment]
I should to use:
`listing.card.documentReference!.getDocument(completion: { (snapshot, err) in })`
instead of:
`listing.card.get({ (card, error) in })`
