### ISSUE TITLE
Use Firebase iOS SDK v5.6.0

### ISSUE THREAD

**Issue by sgr-ksmt** [1amageek/Pring#43]
I want Pring to correspond to Firebase iOS SDK v5.6.0.
Would you please upgrade Pring?

**Comment by 1amageek** [comment]
@sgr-ksmt There seems to be changes in GeoPoint, so it will take some time to fix it.
You can use the current version by fixing Firebase to 5.5.0.

**Comment by 1amageek** [comment]
@sgr-ksmt done
