### ISSUE TITLE
Storage is hard-coded

### ISSUE THREAD

**Issue by mickeyreiss** [1amageek/Pring#45]
Storage is hard-coded in `Object`. As a result, [multi-project configs](https://firebase.google.com/docs/configure/) are not possible with Pring.

Here are the culprits:

https://github.com/1amageek/Pring/blob/4288e82c6cee52a1f5d91ff8812a97ea45acb6f1/Pring/Object.swift#L36

and

https://github.com/1amageek/Pring/blob/4288e82c6cee52a1f5d91ff8812a97ea45acb6f1/Pring/Object.swift#L47

Pring should have an interface for injecting a custom `FIRApp`, in order to override the default `Storage.storage` reference with `Storage.storage(app: passedInValue)`.

**Comment by 1amageek** [comment]
I have not tried it but it should be possible.

Override with the required Document.

``` swift
@objcMembers
class YourDocument: Object {

  override class var storageRef: StorageReference {
    let app = FirebaseApp.app(name: "secondary")!
    return Storage.storage(app).reference().child(self.path)
  }

  override var storageRef: {
    let app = FirebaseApp.app(name: "secondary")!
    return Storage.storage(app).reference().child(self.path)
  }

}
```

**Comment by mickeyreiss** [comment]
Thanks, we will try this. It looks like this will work for us.
