### ISSUE TITLE
Query does not work

### ISSUE THREAD

**Issue by nkmrh** [1amageek/Pring#5]
Even with the code like below all posts will be retrieved.

```swift
dataSource = Post.order(by: \Post.createdAt).limit(to: 1).dataSource()
...
}.listen()
```

**Comment by 1amageek** [comment]
Thank you.
I will fix it in the next version.

**Comment by raisumm** [comment]
I want someone to fix....!

**Comment by 1amageek** [comment]
I have released a new version.

Please use version `0.2.2`

**Comment by nkmrh** [comment]
@1amageek Thank you for the quick fix! I immediately tried it on my project and the query worked. 👍  but I found the following two problems. Maybe there are other bugs... 😿  I'd like you to check it.

1. The callback is no longer called in real time when updating the database.

```swift
dataSource = Post.where(\Post.isDeleted, isEqualTo: false)
            .order(by: \Post.createdAt, descending: true)
            .limit(to: 50)
            .dataSource()
            .on {  _, _ in
                // It is called only once...
            }
            .listen()
```

2. Unable to get document of sub collection.

```swift
post.videos.order(by: \Video.createdAt).dataSource()
            .onCompleted {  _, videos in
                // `post.videos.cout` is 1 but videos is empty...
            }
            .get()
```
