### ISSUE TITLE
Clarification of use case of Relation

### ISSUE THREAD

**Issue by shukob** [1amageek/Pring#51]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 10.1 (10B61)
  * Pring version: 0.15.0

### [REQUIRED] Step 3: Describe the problem
I want to know the intended differences between Relation and Reference.
In my understanding, Relation is a wrapper of the pattern in which we save an id of a collection object instead of a DocumentReference to it. Is it collect?

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by 1amageek** [comment]
Hi @shukob 
Thank you for your message.

This is for you.
https://speakerdeck.com/1amageek/firestore-database-design

**Comment by shukob** [comment]
Thank you for a good reference document.
A security consideration mentioned in the document with respect to a separation of collections was helpful.
I concluded that what I imagined for the 'Relation' object was correct.
