### ISSUE TITLE
Feature Request: use superclassMirror to make Object subclass inheritable

### ISSUE THREAD

**Issue by shukob** [1amageek/Pring#53]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version:  10.1 (10B61)
  * Pring version: 0.15.2

### [REQUIRED] Step 3: Describe the problem
Currently only leaf class properties can be handled. It is useful if we can have class hierarchy using `Object` subclasses.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by shukob** [comment]
Re https://github.com/1amageek/Pring/pull/56

**Comment by 1amageek** [comment]
@shukob Thank for your PR. I released new versions.
Please also add usage instructions to README.🙏🏻
