### ISSUE TITLE
Filtering query by array

### ISSUE THREAD

**Issue by MRzr** [1amageek/Pring#6]
Hi,

i want to ask about filtering query by array, filtering data after query is possible but it isn't good solution in case of large amounts of data . I know this can be kind of tricky, because firestore itself doesn't have this type of query. Their solution is to use map of values [https://firebase.google.com/docs/firestore/solutions/arrays](url) .

Do you have any solution for this problem? Or are you planing to implement something like this?

Thank you very much for you time and good work.

**Comment by 1amageek** [comment]
Firestore uses arrays only when guaranteeing order. When holding a large amount of data, it is better to use SubCollection. Pring provides multiple functions to make it easier. I will introduce those functions.

- ReferenceCollection
- NestedCollection
- DataSource

__ReferenceCollection__
A ReferenceCollection can hold only the id in SubCollection and define the relationship between Object and Object.

__NestedCollection__
NestedCollection holds the relationship between Object and Object as a nest.

__DataSource___
DataSource allows you to manipulate SubCollection using queries.

**Comment by ajr80231** [comment]
How would i set the datasource to filter by the user's name. Such as find all the object who's names are John?
right now I have: 
`self.dataSource = Products.where(\Products.name, isLessThanOrEqualTo: searchBar.text!).dataSource().on({ [weak self] (snapshot, changes) in
//                guard let collectionView: UICollectionView = self?.collectionView else { return }
//                print(snapshot?.count)
//                switch changes {
//                case .initial:
//                    collectionView.reloadData()
//                case .update(let deletions, let insertions, let modifications):
//                    collectionView.performBatchUpdates({
//                        collectionView.insertItems(at: insertions.map { IndexPath(row: $0, section: 0) })
//                        collectionView.deleteItems(at: deletions.map { IndexPath(row: $0, section: 0) })
//                        collectionView.reloadItems(at: modifications.map { IndexPath(row: $0, section: 0) })
//                    }, completion: nil)
//                case .error(let error):
//                    print(error)
//                }
//            }).listen()`
