### ISSUE TITLE
Crashes on DataSource and Object

### ISSUE THREAD

**Issue by MRzr** [1amageek/Pring#7]
I have been testing Pring with my app and (me + 2 testers) and we've encountered quite high frequency of crashes. It seems most problematic part is when using data source from nested or reference collection. I am using simple query.dataSource().onCompleted({...}).get() on these objectes

<img width="1258" alt="snimek obrazovky 2017-12-08 v 9 58 11" src="https://user-images.githubusercontent.com/3685858/33759020-00b6dbba-dc01-11e7-9754-2d7103a513b2.png">
<img width="1270" alt="snimek obrazovky 2017-12-08 v 9 57 54" src="https://user-images.githubusercontent.com/3685858/33759021-00d82248-dc01-11e7-8af2-34e1547169fe.png">
<img width="1262" alt="snimek obrazovky 2017-12-08 v 9 57 29" src="https://user-images.githubusercontent.com/3685858/33759022-00f156aa-dc01-11e7-9111-b40bea5301dd.png">

**Comment by 1amageek** [comment]
Please send detailed logs.
I also want reproducible code.

**Comment by 1amageek** [comment]
fixed
